# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- name: URL           # hardcoded value
  value: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
   export SFDX_AUTOUPDATE_DISABLE=false
   export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
   export SFDX_DOMAIN_RETRY=300
   export SFDX_DISABLE_APP_HUB=true
   export SFDX_LOG_LEVEL=DEBUG
  displayName: 'Run a multi-line script'