# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- name: URL           # hardcoded value
  value: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    
steps:
# Download Secure File
# Download a secure file to a temporary location on the build or release agent
- task: DownloadSecureFile@1
  inputs:
    secureFile: server.key
  displayName: 'Download server.key from secure location'
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
   #TODO: currently the below encryption key is part of git-repo which needs to be avoided or use key vault to store and retreieve the cert
   #openssl aes-256-cbc -K $encrypted_3ff541c4128f_key -iv $encrypted_3ff541c4128f_iv -in assets/server.key.enc -out assets/server.key -d
   export SFDX_AUTOUPDATE_DISABLE=false
   export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
   export SFDX_DOMAIN_RETRY=300
   export SFDX_DISABLE_APP_HUB=true
   export SFDX_LOG_LEVEL=DEBUG
  displayName: 'Run variable script'

- script: |
   mkdir sfdx
   wget -qO- $URL | tar xJ -C sfdx --strip-components 1
   "./sfdx/install"
   export PATH=./sfdx/$(pwd):$PATH
   sfdx --version
   sfdx plugins --core
   sfdx force:auth:jwt:grant --clientid $(CONSUMERKEY) --username $(USERNAME) --jwtkeyfile $env:DOWNLOADSECUREFILE_SECUREFILEPATH --setdefaultdevhubusername -a HubOrg
  displayName: 'Run sfdx script'

- script: |
   sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
   sfdx force:org:display -u ciorg
   sfdx force:source:push -u ciorg
   sfdx force:apex:test:run -u ciorg --wait 10
   sfdx force:org:delete -u ciorg -p
  displayName: 'Run Scratch Org deployment script'  
