# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- name: URL           # hardcoded value
  value: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
   openssl aes-256-cbc -K $encrypted_3ff541c4128f_key -iv $encrypted_3ff541c4128f_iv -in assets/server.key.enc -out assets/server.key -d
   export SFDX_AUTOUPDATE_DISABLE=false
   export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
   export SFDX_DOMAIN_RETRY=300
   export SFDX_DISABLE_APP_HUB=true
   export SFDX_LOG_LEVEL=DEBUG
  displayName: 'Run variable script'

- script: |
   mkdir sfdx
   wget -qO- $URL | tar xJ -C sfdx --strip-components 1
   "./sfdx/install"
   export PATH=./sfdx/$(pwd):$PATH
   sfdx --version
   sfdx plugins --core
   sfdx force:auth:jwt:grant --clientid 3MVG9zlTNB8o8BA3Yt71uIGGnSR7afF7_7rQOQSto1mb0VQ5ov4lYLLqTxsltqyXSc4ig.ejwlUR25FIEze9m --username heruwala@resourceful-raccoon-fjl5g3.com --jwtkeyfile assets/server.key --setdefaultdevhubusername -a HubOrg
  displayName: 'Run sfdx script'

- script: |
   sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
   sfdx force:org:display -u ciorg
   sfdx force:source:push -u ciorg
   sfdx force:apex:test:run -u ciorg --wait 10
   sfdx force:org:delete -u ciorg -p
  displayName: 'Run Scratch Org deployment script'  